server {
  listen 80;
  root /usr/share/nginx/html;
  location = /index.html { internal; }
  location / {
    add_header Retry-After 30 always;
    add_header Cache-Control "no-store" always;
    error_page 503 /index.html;
    return 503;
  }
}
